// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbOK89tMoIRRXOEYQtktwM3wVZjn57dQ8',
    appId: '1:723965658410:web:c325f6733ecd361bae0a53',
    messagingSenderId: '723965658410',
    projectId: 'endeavour-40499',
    authDomain: 'endeavour-40499.firebaseapp.com',
    databaseURL: 'https://endeavour-40499-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'endeavour-40499.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAROvrgXde9H7PEwq-6Ssv2ApmE2jqn_4o',
    appId: '1:723965658410:android:63f2ba8a1f3677bdae0a53',
    messagingSenderId: '723965658410',
    projectId: 'endeavour-40499',
    databaseURL: 'https://endeavour-40499-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'endeavour-40499.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgGhqlxUYa5_ftkCJoAHnN3Kl4NAjH8eI',
    appId: '1:723965658410:ios:a7b302799fcb404eae0a53',
    messagingSenderId: '723965658410',
    projectId: 'endeavour-40499',
    databaseURL: 'https://endeavour-40499-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'endeavour-40499.appspot.com',
    iosBundleId: 'com.example.endeavour',
  );
}
